name: CI/CD MLflow to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install MLflow
        run: pip install mlflow==2.19.0 pandas numpy scikit-learn

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd MLProject
          # Membaca Run ID yang dihasilkan oleh modelling.py
          RUN_ID=$(cat run_id.txt)
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/student_dropout_model:latest"
          
          echo "Membangun Docker Image untuk Run ID: $RUN_ID..."
          mlflow models build-docker -m runs:/$RUN_ID/model -n $IMAGE_NAME
          
          echo "Mendorong Image ke Docker Hub..."
          docker push $IMAGE_NAME